apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: init
  name: init
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: init
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
