apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redismod
  name: redismod
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: redismod
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
