apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: server
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
