# config file version
apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://mars-redisedge_prometheus_1:9090
  isDefault: true
  version: 1
  editable: true

